import { Router } from "express";
import AuthRouter from "./src/routes/auth";
import CargaRouter from "./src/routes/cargas";
import ClienteRouter from "./src/routes/clientes";
import EstoqueRouter from "./src/routes/estoques";
import FechamentoRouter from "./src/routes/fechamento";
import FinalizadoraRouter from "./src/routes/finalizadoras";
import FornecedorRouter from "./src/routes/fornecedor";
import FuncionarioRouter from "./src/routes/funcionarios";
import ImpFederalRouter from "./src/routes/impfederal";
import LojaRouter from "./src/routes/lojas";
import NaoFiscalRouter from "./src/routes/naofiscal";
import PrecoRouter from "./src/routes/precos";
import ProdutosRouter from "./src/routes/produtos";
import RelatorioRouter from "./src/routes/relatorio";
import SecaoRouter from "./src/routes/secoes";
import TenantRouter from "./src/routes/tenants";
import TributacaoRouter from "./src/routes/tributacoes";
import UsuarioRouter from "./src/routes/usuarios";
import VendaRouter from "./src/routes/venda";
import CompraRouter from "./src/routes/compra";
import DownloadRouter from "./src/routes/downloads";
import IbptRouter from "./src/routes/ibpt";
import ErroPdvRouter from "./src/routes/erropdv";
import NotificacaoRouter from "./src/routes/notificacoes";
import FeedbackRouter from "./src/routes/feedback";

const router = Router();
router.use(ProdutosRouter);
router.use(SecaoRouter);
router.use(TributacaoRouter);
router.use(PrecoRouter);
router.use(LojaRouter);
router.use(ClienteRouter);
router.use(FuncionarioRouter);
router.use(ImpFederalRouter);
router.use(EstoqueRouter);
router.use(FinalizadoraRouter);
router.use(RelatorioRouter);
router.use(VendaRouter);
router.use(AuthRouter);
router.use(CargaRouter);
router.use(NaoFiscalRouter);
router.use(FechamentoRouter);
router.use(FornecedorRouter);
router.use(TenantRouter);
router.use(UsuarioRouter);
router.use(CompraRouter);
router.use(DownloadRouter);
router.use(IbptRouter);
router.use(ErroPdvRouter);
router.use(NotificacaoRouter);
router.use(FeedbackRouter);

export default router;
